### PR TITLE
Added Climate variable functions and corresponding csv tables

### PR DESCRIPTION
**Pull request by okanji**
- A `functions.R` file has been added to the `derivedVariables` folder containing all the functions for the derived variables.
- Corresponding csv tables have been added to `optimizedParameterTables`
- I have included the markdown file that I used to create these functions as it may make it easier to test these functions on their own. This can be deleted later.

This completes the _create function_ and _create csv of table_ tasks in the following functions: #5 #6 #7 #8 #9 #10

### CODE REVIEW

**Comment by cmahony** [comment]
@okanji i'm on the road today so i haven't reviewed the pull request but i merged it into main and i will review it tomorrow. how are things going? let's check in once i've had a chance to review, but until then do let me know if you need any input.

**Comment by okanji** [comment]
Hi Colin, 

I think that one is outdated re our last conversation to pre compute. Sorry I should have brought it down after our last conversation. I can easily revert it.

Yes let's check in tomorrow. All is going well, have been pre computing the climate variables am almost done. 

Are you free at 11am tomorrow morning (your time)?

Thanks,

Oamar

**Comment by cmahony** [comment]
oops. damn. 
can we chat on tuesday instead? sometime between 10am and noon would be ideal for me.

**Comment by okanji** [comment]
Yes Tuesday works, and I’ll go ahead and revert that pull request once I have the one I’m working on ready, its quite easy with GitHub.

Can we do 11am on Tuesday? If so I’ll send you a Zoom invite.

Thanks

**Comment by cmahony** [comment]
yup that sounds great. 11am on tuesday.

**Pull request merged**
