### PR TITLE
Precomputed derived variables and added them to the app

### PR DESCRIPTION
**Pull request by okanji**
- Refracted precompute script to include derived variables
- Added derived variables to shiny app
- Reactively remove month/season values if variable does not have that time period
- Added plot png and data csv download buttons

### CODE REVIEW

**Comment by okanji** [comment]
This pr resolved #6 #7 #8 #9 #10 #11 #13

**Comment by cmahony** [comment]
@okanji there are a couple of merge conflicts in this pull request and i'm unsure of how to resolve them. can you advise?

**Comment by okanji** [comment]
Hi Colin, I’ll resolve them tomorrow!

**Comment by cmahony** [comment]
thanks oamar!

**Pull request merged**
